spring:
  devtools.restart.enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 60000
      connection-timeout: 20000
  jpa:
    open-in-view: false
    hibernate.ddl-auto: ${HIBERNATE_DDL_AUTO:update}
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 270228412426-eu2nbfvcc7d3u3a18tpa6scj44i9s23i.apps.googleusercontent.com
            client-secret: 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

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
